export type Severity = 'Critical' | 'High' | 'Medium' | 'Low' | 'Informational';
export type Finding = { id: string; title: string; severity: Severity; cvss: number; confidence: string; category: string; asset: string; status: string; detected: string; summary: string; impact: string; fix: string; owner: string; evidence: string[] };
export type Assessment = { id: string; name: string; target: string; status: string; findings: number; score: number; progress: number; lastRun: string; logs?: string[] };
export const assessments: Assessment[] = [
 {id:'world-monitor',name:'World Monitor Security Assessment',target:'world-monitor.local',status:'Completed',findings:51,score:72,progress:100,lastRun:'27 Sep 2026'},
 {id:'api-security',name:'API Security Assessment',target:'api.world-monitor.local',status:'Running',findings:14,score:64,progress:76,lastRun:'27 Sep 2026'},
 {id:'prerelease',name:'Pre-release Application Audit',target:'staging.world-monitor.local',status:'Scheduled',findings:8,score:81,progress:0,lastRun:'25 Sep 2026'},
 {id:'dependencies',name:'Dependency Security Scan',target:'world-monitor/repository',status:'Completed',findings:6,score:87,progress:100,lastRun:'23 Sep 2026'},
];
export const findings: Finding[] = [
 {id:'FND-001',title:'Missing Authorization Check',severity:'Critical',cvss:9.1,confidence:'High',category:'Authorization',asset:'/api/v1/admin/users',status:'Open',detected:'27 Sep 2026',summary:'An authenticated user can access administrative user records without an authorization check.',impact:'Unauthorized access to sensitive user data and administrative actions.',fix:'Enforce server-side role checks on every administrative route and add negative authorization tests.',owner:'Unassigned',evidence:['EV-1042','EV-1043','EV-1044']},
 {id:'FND-002',title:'Exposed Debug Endpoint',severity:'High',cvss:8.2,confidence:'High',category:'API Security',asset:'/api/debug/config',status:'Validated',detected:'26 Sep 2026',summary:'A production-accessible debug endpoint reveals internal configuration details.',impact:'An attacker may use infrastructure details to target connected services.',fix:'Disable debug endpoints in production and restrict them at the gateway.',owner:'Priya Shah',evidence:['EV-1045']},
 {id:'FND-003',title:'Outdated Client Dependency',severity:'Medium',cvss:6.5,confidence:'Medium',category:'Dependencies',asset:'frontend / charting',status:'In progress',detected:'25 Sep 2026',summary:'A client dependency contains a published vulnerability in an outdated release.',impact:'Potential client-side compromise under specific interaction conditions.',fix:'Upgrade to the patched release and run regression tests.',owner:'Arjun Mehta',evidence:['EV-1046']},
 {id:'FND-004',title:'Insecure Session Cookie',severity:'High',cvss:7.8,confidence:'High',category:'Authentication',asset:'world-monitor.local',status:'Open',detected:'24 Sep 2026',summary:'Session cookies lack the Secure attribute in one application path.',impact:'Session information may be exposed over an unencrypted connection.',fix:'Set Secure, HttpOnly and SameSite on all session cookies.',owner:'Nisha Rao',evidence:['EV-1047']},
 {id:'FND-005',title:'Overly Permissive CORS Policy',severity:'Medium',cvss:5.9,confidence:'Medium',category:'Configuration',asset:'/api/v1/metrics',status:'Open',detected:'23 Sep 2026',summary:'Cross-origin requests accept a broader set of origins than intended.',impact:'Untrusted origins may access responses when combined with user credentials.',fix:'Allowlist only approved origins and test credentialed requests.',owner:'Unassigned',evidence:['EV-1048']},
 {id:'FND-006',title:'Missing Content Security Policy',severity:'Low',cvss:3.7,confidence:'High',category:'Client Security',asset:'frontend',status:'Verified',detected:'21 Sep 2026',summary:'The application does not send a restrictive content security policy.',impact:'Client-side injection defenses are weaker than recommended.',fix:'Add a restrictive CSP and validate all permitted script sources.',owner:'Priya Shah',evidence:['EV-1049']},
];
export const evidence = [
 {id:'EV-1042',type:'HTTP Request',time:'27 Sep 2026 · 09:42:11',source:'Authorization check',confidence:'High',finding:'FND-001',content:'GET /api/v1/admin/users HTTP/1.1\nHost: world-monitor.local\nAuthorization: Bearer [REDACTED]\nAccept: application/json\nX-Assessment-ID: WM-2026-09',comparison:'Expected: 403 Forbidden for a non-admin account.'},
 {id:'EV-1043',type:'HTTP Response',time:'27 Sep 2026 · 09:42:12',source:'API response capture',confidence:'High',finding:'FND-001',content:'HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n  "users": [\n    { "id": "usr_129", "role": "admin", "email": "[REDACTED]" },\n    { "id": "usr_130", "role": "analyst", "email": "[REDACTED]" }\n  ],\n  "total": 2\n}',comparison:'Expected: 403 Forbidden. Observed: 200 OK with user records.'},
 {id:'EV-1044',type:'Scanner Output',time:'27 Sep 2026 · 09:42:15',source:'Access control validation',confidence:'High',finding:'FND-001',content:'CHECK: admin endpoint access as analyst\nRESULT: authorization bypass confirmed\nEXPECTED STATUS: 403\nOBSERVED STATUS: 200\nSENSITIVE FIELDS: role, email\nREPRODUCIBLE: 3 / 3 attempts',comparison:'Baseline: an admin account is permitted to request this resource.'},
 {id:'EV-1045',type:'API Response',time:'26 Sep 2026 · 14:16:32',source:'Endpoint discovery',confidence:'High',finding:'FND-002',content:'GET /api/debug/config → 200 OK\n{ "environment": "production", "services": ["metrics", "worker"], "secrets": "[REDACTED]" }',comparison:'Expected: debug routes disabled in production.'},
 {id:'EV-1046',type:'Dependency Information',time:'25 Sep 2026 · 11:03:18',source:'Dependency inventory',confidence:'Medium',finding:'FND-003',content:'PACKAGE: chart-renderer\nINSTALLED: 2.4.1\nPATCHED: 2.4.8\nADVISORY: Client-side data handling issue',comparison:'Patched release: 2.4.8.'},
 {id:'EV-1047',type:'HTTP Response',time:'24 Sep 2026 · 10:21:09',source:'Session audit',confidence:'High',finding:'FND-004',content:'Set-Cookie: session=[REDACTED]; HttpOnly; SameSite=Lax\nMissing attribute: Secure',comparison:'Expected: Secure; HttpOnly; SameSite=Lax.'},
 {id:'EV-1048',type:'Configuration',time:'23 Sep 2026 · 16:44:26',source:'Header audit',confidence:'Medium',finding:'FND-005',content:'Access-Control-Allow-Origin: *\nAccess-Control-Allow-Credentials: true',comparison:'Expected: explicit allowlisted origins.'},
 {id:'EV-1049',type:'HTTP Response',time:'21 Sep 2026 · 08:12:20',source:'Header audit',confidence:'High',finding:'FND-006',content:'HTTP/1.1 200 OK\nContent-Type: text/html\nContent-Security-Policy: [NOT PRESENT]',comparison:'Expected: restrictive Content-Security-Policy header.'},
];
export const assets = [
 {id:'app',label:'World Monitor',type:'Application',state:'Warning',risk:72,findings:3,x:40,y:210},
 {id:'frontend',label:'Web Frontend',type:'Frontend',state:'Secure',risk:24,findings:1,x:325,y:70},
 {id:'api',label:'Core API',type:'API',state:'Critical',risk:91,findings:3,x:325,y:280},
 {id:'auth',label:'Auth Service',type:'Service',state:'Warning',risk:68,findings:1,x:610,y:70},
 {id:'admin',label:'Admin Users',type:'Endpoint',state:'Critical',risk:91,findings:1,x:610,y:250},
 {id:'metrics',label:'Metrics API',type:'Endpoint',state:'Vulnerable',risk:59,findings:1,x:610,y:440},
 {id:'db',label:'User Database',type:'Database',state:'Warning',risk:75,findings:1,x:895,y:170},
 {id:'third',label:'Telemetry SDK',type:'Dependency',state:'Secure',risk:18,findings:0,x:895,y:400},
];
export const trend = [{date:'01 Sep',score:54,risk:72,open:54,resolved:2},{date:'05 Sep',score:57,risk:68,open:49,resolved:7},{date:'09 Sep',score:59,risk:64,open:46,resolved:10},{date:'13 Sep',score:61,risk:61,open:42,resolved:14},{date:'17 Sep',score:64,risk:55,open:38,resolved:18},{date:'21 Sep',score:67,risk:49,open:34,resolved:22},{date:'25 Sep',score:70,risk:43,open:31,resolved:25},{date:'27 Sep',score:72,risk:40,open:28,resolved:28}];
export const severityData = [{name:'Critical',value:3},{name:'High',value:12},{name:'Medium',value:18},{name:'Low',value:7},{name:'Informational',value:11}];
export const categories = [{name:'Authorization',count:14},{name:'API Security',count:11},{name:'Dependencies',count:9},{name:'Authentication',count:8},{name:'Configuration',count:6},{name:'Client Security',count:3}];

