import { Link } from '@tanstack/react-router';
import { ArrowDownRight, ArrowUpRight, ChevronRight, Search, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { type ReactNode } from 'react';
import { type Severity } from '@/lib/sentinel-data';
export const severityColor:Record<Severity,string>={Critical:'text-critical',High:'text-high',Medium:'text-medium',Low:'text-low',Informational:'text-muted-foreground'};
export const severityBg:Record<Severity,string>={Critical:'bg-critical/10 border-critical/25',High:'bg-high/10 border-high/25',Medium:'bg-medium/10 border-medium/25',Low:'bg-low/10 border-low/25',Informational:'bg-muted border-border'};
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:string}){const tones:Record<string,string>={Critical:'text-critical bg-critical/10 border-critical/25',High:'text-high bg-high/10 border-high/25',Medium:'text-medium bg-medium/10 border-medium/25',Low:'text-low bg-low/10 border-low/25',Informational:'text-muted-foreground bg-muted border-border',Completed:'text-success bg-success/10 border-success/25',Verified:'text-success bg-success/10 border-success/25',Running:'text-low bg-low/10 border-low/25',Validated:'text-violet bg-violet/10 border-violet/25',Open:'text-high bg-high/10 border-high/25',Failed:'text-critical bg-critical/10 border-critical/25',neutral:'text-muted-foreground bg-muted border-border'};return <span className={`inline-flex whitespace-nowrap items-center rounded border px-2 py-0.5 text-[11px] font-semibold ${tones[tone]||tones['neutral']}`}>{children}</span>}
export function PageHeading({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description?:string;actions?:ReactNode}){return <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div className="min-w-0"><div className="eyebrow mb-2">{eyebrow||'SECURITY OPERATIONS'}</div><h1 className="text-2xl font-semibold leading-tight sm:text-[28px]">{title}</h1>{description&&<p className="mt-2 text-sm text-muted-foreground">{description}</p>}</div>{actions&&<div className="flex shrink-0 flex-wrap gap-2">{actions}</div>}</div>}
export function Panel({title,sub,action,children,className=''}:{title?:string;sub?:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={`panel min-w-0 ${className}`}><div className="p-5">{title&&<div className="mb-5 flex items-start justify-between gap-3"><div><h2 className="section-title">{title}</h2>{sub&&<p className="mt-1 text-xs text-muted-foreground">{sub}</p>}</div>{action}</div>}{children}</div></section>}
export function Metric({label,value,change,icon:Icon,tone='primary',foot}:{label:string;value:string|number;change?:string;icon?:any;tone?:string;foot?:string}){const colors:Record<string,string>={primary:'text-primary',critical:'text-critical',high:'text-high',success:'text-success',violet:'text-violet'};return <div className="panel relative min-h-[132px] min-w-0 p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><span className="min-w-0 text-xs font-medium text-muted-foreground">{label}</span>{Icon&&<Icon className={`${colors[tone]||colors['primary']} shrink-0`} size={18}/>}</div><div className="mt-5 flex flex-wrap items-end justify-between gap-2"><strong className="min-w-0 text-[24px] leading-none font-semibold tabular-nums sm:text-[29px]">{value}</strong>{change&&<span className={`flex shrink-0 items-center gap-0.5 text-xs font-medium ${change.startsWith('+')?'text-success':'text-muted-foreground'}`}>{change.startsWith('+')?<ArrowUpRight size={13}/>:<ArrowDownRight size={13}/>} {change}</span>}</div>{foot&&<div className="mt-2 text-[11px] text-muted-foreground">{foot}</div>}</div>}
export function SearchField({value,onChange,placeholder='Search...'}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <div className="relative min-w-0"><Search size={15} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="h-9 w-full rounded-md border border-border bg-secondary pl-9 pr-3 text-xs text-foreground placeholder:text-muted-foreground focus:border-primary focus:outline-none"/></div>}
export function Filter({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:string[];label:string}){return <select aria-label={label} value={value} onChange={e=>onChange(e.target.value)} className="h-9 min-w-[112px] rounded-md border border-border bg-secondary px-2 text-xs text-foreground"><option value="All">All {label}</option>{options.map(o=><option key={o} value={o}>{o}</option>)}</select>}
export function Empty({text='No matching results'}:{text?:string}){return <div className="flex flex-col items-center justify-center py-16 text-center"><ShieldCheck size={28} className="mb-3 text-muted-foreground"/><p className="text-sm text-muted-foreground">{text}</p></div>}
export function SectionLink({to,children,params}:{to:any;children:ReactNode;params?:any}){return <Link to={to} params={params} className="inline-flex items-center gap-1 text-xs font-medium text-primary hover:text-foreground">{children}<ChevronRight size={13}/></Link>}
export function Action({children,onClick,variant='outline',icon:Icon,disabled=false}:{children:ReactNode;onClick?:()=>void;variant?:'outline'|'default'|'ghost';icon?:any;disabled?:boolean}){return <Button size="sm" variant={variant} onClick={onClick} disabled={disabled} className="h-9 gap-2 text-xs">{Icon&&<Icon size={14}/>} {children}</Button>}
