import { useMemo, useState } from 'react';
import { Link } from '@tanstack/react-router';
import { Activity, ArrowDownRight, ArrowRight, ArrowUpRight, Bell, CheckCircle2, CircleDot, Download, Filter, Globe2, Radar, RefreshCw, Search, ShieldAlert, ShieldCheck, Siren, Target, X } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis, Bar, BarChart } from 'recharts';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Badge } from './sentinel-ui';
import { useSentinel } from '@/lib/sentinel-store';
import { assets, trend, type Finding, type Severity } from '@/lib/sentinel-data';

const severityTones: Record<Severity, string> = { Critical: 'critical', High: 'high', Medium: 'medium', Low: 'low', Informational: 'muted-foreground' };
const severityOrder: Severity[] = ['Critical', 'High', 'Medium', 'Low'];
const css = (name: string) => `var(--${name})`;
const chartTooltip = { contentStyle: { background: css('panel'), border: `1px solid ${css('border')}`, borderRadius: 6, color: css('foreground'), fontSize: 11 }, itemStyle: { color: css('foreground') } };
const fullTrend = trend.map((item, index) => ({ ...item, traffic: 320 + index * 26 + ([24, -9, 33, -18, 12, -24, 38, -6][index] ?? 0), threats: 64 - index * 5 + (index % 2) * 6 }));

function Panel({ title, note, action, children, className = '' }: { title: string; note?: string; action?: React.ReactNode; children: React.ReactNode; className?: string }) {
  return <section className={`command-panel min-w-0 ${className}`}><div className="flex min-h-12 items-center justify-between gap-3 border-b border-border px-4 py-3"><div className="min-w-0"><h2 className="truncate text-[12px] font-semibold text-foreground">{title}</h2>{note && <p className="mt-0.5 truncate text-[10px] text-muted-foreground">{note}</p>}</div>{action}</div><div className="p-4">{children}</div></section>;
}
function Kpi({ label, value, sub, icon: Icon, tone = 'primary', direction = 'up' }: { label: string; value: string; sub: string; icon: typeof Activity; tone?: string; direction?: 'up' | 'down' }) {
  return <div className="command-panel relative min-w-0 px-4 py-3.5"><div className="flex items-center justify-between gap-2"><span className="truncate text-[10px] font-medium uppercase text-muted-foreground">{label}</span><Icon size={15} className={`shrink-0 text-${tone}`} /></div><div className="mt-3 flex items-end justify-between gap-2"><strong className="truncate text-[25px] leading-none font-semibold tabular-nums text-foreground">{value}</strong><span className={`flex shrink-0 items-center text-[10px] text-${tone}`}>{direction === 'up' ? <ArrowUpRight size={12}/> : <ArrowDownRight size={12}/>}</span></div><p className="mt-2 truncate text-[10px] text-muted-foreground">{sub}</p></div>;
}
function downloadCsv(findings: Finding[]) {
  const rows = [['ID', 'Title', 'Severity', 'Asset', 'Status', 'Owner'], ...findings.map(f => [f.id, f.title, f.severity, f.asset, f.status, f.owner])];
  const csv = rows.map(row => row.map(cell => `"${String(cell).replaceAll('"', '""')}"`).join(',')).join('\n');
  const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' }));
  const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'sentinel-findings.csv'; anchor.click(); URL.revokeObjectURL(url);
}
export function SentinelOverview() {
  const { findings, assessments, selectedAssessment, setSelectedAssessment, updateFinding, notify } = useSentinel();
  const [period, setPeriod] = useState<'7D' | '30D' | '90D'>('30D');
  const [severity, setSeverity] = useState('All');
  const [query, setQuery] = useState('');
  const [selected, setSelected] = useState<Finding | null>(null);
  const [lastRefreshed, setLastRefreshed] = useState('Just now');
  const active = assessments.find(a => a.id === selectedAssessment) ?? assessments[0];
  const visibleTrend = period === '7D' ? fullTrend.slice(-4) : fullTrend;
  const filtered = useMemo(() => findings.filter(f => (severity === 'All' || f.severity === severity) && `${f.title} ${f.asset} ${f.id}`.toLowerCase().includes(query.toLowerCase())), [findings, severity, query]);
  const open = findings.filter(f => f.status !== 'Verified').length;
  const counts = severityOrder.map(name => ({ name, value: findings.filter(f => f.severity === name).length, color: css(severityTones[name]) }));
  const categoryCounts = [...new Set(findings.map(f => f.category))].map(name => ({ name, count: findings.filter(f => f.category === name).length }));
  const statusAction = (finding: Finding) => { const status = finding.status === 'Verified' ? 'Open' : 'Verified'; updateFinding(finding.id, { status }); setSelected({ ...finding, status }); notify(`${finding.id} marked ${status.toLowerCase()}`); };
  return <div className="space-y-4 pb-10">
    <div className="flex flex-col justify-between gap-4 border-b border-border pb-5 xl:flex-row xl:items-end">
      <div className="min-w-0"><div className="mb-2 flex items-center gap-2 text-[10px] font-semibold uppercase text-primary"><span className="h-1.5 w-1.5 rounded-full bg-success shadow-[0_0_10px_var(--success)]"/> Security operations / Overview <span className="ml-1 rounded border border-primary/30 bg-primary/10 px-1.5 py-0.5 text-[9px] text-primary">DEMO DATA</span></div><h1 className="text-[25px] font-semibold leading-tight text-foreground sm:text-[30px]">SENTINEL <span className="font-normal text-muted-foreground">/ Command Center</span></h1><p className="mt-1 text-xs text-muted-foreground">One view of exposure, assessments, incidents, and remediation.</p></div>
      <div className="flex flex-wrap items-center gap-2"><select aria-label="Assessment" className="h-8 max-w-[210px] rounded-md border border-border bg-secondary px-2 text-[11px] text-foreground" value={selectedAssessment} onChange={e => setSelectedAssessment(e.target.value)}>{assessments.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select><Button variant="outline" size="sm" title="Refresh view" aria-label="Refresh view" onClick={() => { setLastRefreshed(new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })); notify('Dashboard refreshed'); }}><RefreshCw size={14}/></Button><Button size="sm" onClick={() => downloadCsv(filtered)}><Download size={14}/> Export CSV</Button></div>
    </div>
    <div className="grid grid-cols-2 gap-2.5 md:grid-cols-3 xl:grid-cols-6"><Kpi label="Security score" value={`${active?.score ?? 72}/100`} sub="+8 since last review" icon={ShieldCheck} tone="success"/><Kpi label="Critical issues" value={String(findings.filter(f => f.severity === 'Critical' && f.status !== 'Verified').length)} sub="Needs immediate action" icon={Siren} tone="critical" direction="down"/><Kpi label="Open findings" value={String(open)} sub={`${findings.length} total in workspace`} icon={ShieldAlert} tone="high" direction="down"/><Kpi label="Assets monitored" value="48" sub="8 mapped in this view" icon={Globe2} tone="low"/><Kpi label="Active scans" value={String(assessments.filter(a => a.status === 'Running').length)} sub="Across 4 assessments" icon={Radar} tone="primary"/><Kpi label="Remediated" value={String(findings.filter(f => f.status === 'Verified').length)} sub="Verified fixes" icon={CheckCircle2} tone="success"/></div>
    <div className="grid gap-3 lg:grid-cols-12">
      <Panel title="Security posture" note="Score and risk movement over time" className="lg:col-span-6" action={<div className="flex gap-0.5 rounded border border-border bg-secondary p-0.5">{(['7D','30D','90D'] as const).map(p => <Button key={p} variant={period === p ? 'secondary' : 'ghost'} size="sm" className={`h-6 px-2 text-[10px] ${period === p ? 'text-primary' : 'text-muted-foreground'}`} onClick={() => setPeriod(p)}>{p}</Button>)}</div>}><div className="h-[190px] w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={visibleTrend} margin={{ top: 4, right: 8, bottom: 0, left: -25 }}><defs><linearGradient id="score-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor={css('primary')} stopOpacity={.28}/><stop offset="100%" stopColor={css('primary')} stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke={css('border')} strokeDasharray="3 5" vertical={false}/><XAxis dataKey="date" tick={{ fill: css('muted-foreground'), fontSize: 9 }} axisLine={false} tickLine={false}/><YAxis domain={[30, 90]} tick={{ fill: css('muted-foreground'), fontSize: 9 }} axisLine={false} tickLine={false}/><Tooltip {...chartTooltip}/><Area dataKey="score" stroke={css('primary')} fill="url(#score-fill)" strokeWidth={2.5} name="Security score"/><Area dataKey="risk" stroke={css('high')} fill="transparent" strokeWidth={1.5} strokeDasharray="4 4" name="Risk index"/></AreaChart></ResponsiveContainer></div><div className="mt-1 flex items-center gap-4 text-[10px] text-muted-foreground"><span><i className="mr-1.5 inline-block h-1.5 w-1.5 rounded-full bg-primary"/>Security score</span><span><i className="mr-1.5 inline-block h-1.5 w-1.5 rounded-full bg-high"/>Risk index</span><span className="ml-auto">Updated {lastRefreshed}</span></div></Panel>
      <Panel title="Findings by severity" note="Current issue distribution" className="lg:col-span-3"><div className="relative h-[150px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={counts} innerRadius={48} outerRadius={65} dataKey="value" stroke="none" paddingAngle={4}>{counts.map(c => <Cell key={c.name} fill={c.color}/>)}</Pie><Tooltip {...chartTooltip}/></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><strong className="text-2xl font-semibold">{findings.length}</strong><span className="text-[9px] uppercase text-muted-foreground">findings</span></div></div><div className="mt-1 grid grid-cols-2 gap-2">{counts.map(c => <div key={c.name} className="flex items-center justify-between gap-2 text-[10px]"><span className="flex items-center gap-1.5 text-muted-foreground"><i className={`h-1.5 w-1.5 rounded-full bg-${severityTones[c.name as Severity]}`}/>{c.name}</span><b>{c.value}</b></div>)}</div></Panel>
      <Panel title="Assessment pipeline" note="Scan completion across targets" className="lg:col-span-3" action={<Link to="/assessments" className="text-primary" aria-label="View assessments"><ArrowRight size={15}/></Link>}><div className="space-y-4">{assessments.map(a => <Link to="/assessments/$id" params={{ id: a.id }} key={a.id} className="block group"><div className="mb-1.5 flex items-center justify-between gap-2 text-[10px]"><span className="truncate text-foreground group-hover:text-primary">{a.name}</span><span className="shrink-0 font-semibold text-primary">{a.progress}%</span></div><div className="h-1.5 overflow-hidden rounded bg-secondary"><div className="h-full rounded bg-primary" style={{width:`${a.progress}%`}}/></div></Link>)}</div><div className="mt-4 border-t border-border pt-3 text-[10px] text-muted-foreground">48 assets · 132 endpoints · 76 dependencies</div></Panel>
    </div>
    <div className="grid gap-3 lg:grid-cols-12">
      <Panel title="Threat activity" note="Sample event volume by observation period" className="lg:col-span-4"><div className="h-[145px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={visibleTrend} margin={{top:4,right:0,left:-25,bottom:0}}><CartesianGrid vertical={false} stroke={css('border')} strokeDasharray="3 5"/><XAxis dataKey="date" tick={{ fill: css('muted-foreground'), fontSize: 9 }} axisLine={false} tickLine={false}/><YAxis tick={{ fill: css('muted-foreground'), fontSize: 9 }} axisLine={false} tickLine={false}/><Tooltip {...chartTooltip}/><Bar dataKey="traffic" fill={css('primary')} radius={[2,2,0,0]} name="Events"/></BarChart></ResponsiveContainer></div><div className="mt-2 flex justify-between border-t border-border pt-3 text-[10px]"><span className="text-muted-foreground">Peak activity</span><span className="text-primary">+12.8% vs baseline</span></div></Panel>
      <Panel title="Exposure by asset" note="Risk score of mapped services" className="lg:col-span-4" action={<Link to="/attack-surface" className="text-primary" aria-label="View attack surface"><ArrowRight size={15}/></Link>}><div className="space-y-2.5">{assets.slice(0,5).map(a => <div key={a.id} className="grid grid-cols-[minmax(0,1fr)_2fr_25px] items-center gap-2 text-[10px]"><span className="truncate text-muted-foreground">{a.label}</span><div className="h-1.5 rounded bg-secondary"><div className={`h-full rounded ${a.risk >= 80 ? 'bg-critical' : a.risk >= 60 ? 'bg-high' : 'bg-primary'}`} style={{ width: `${a.risk}%` }}/></div><b className="text-right tabular-nums">{a.risk}</b></div>)}</div><div className="mt-3 border-t border-border pt-3 text-[10px] text-muted-foreground">Highest exposure <span className="float-right text-critical">Core API · 91/100</span></div></Panel>
      <Panel title="Vulnerability categories" note="Issues grouped by weakness" className="lg:col-span-4"><div className="space-y-2.5">{categoryCounts.slice(0,5).map((c,i) => <div key={c.name} className="grid grid-cols-[minmax(0,1fr)_2fr_16px] items-center gap-2 text-[10px]"><span className="truncate text-muted-foreground">{c.name}</span><div className="h-1.5 rounded bg-secondary"><div className={`h-full rounded ${i % 2 ? 'bg-low' : 'bg-violet'}`} style={{ width: `${Math.max(18,c.count / findings.length * 100)}%` }}/></div><b className="text-right">{c.count}</b></div>)}</div><div className="mt-3 border-t border-border pt-3 text-[10px] text-muted-foreground">{categoryCounts.length} categories tracked</div></Panel>
    </div>
    <div className="grid gap-3 lg:grid-cols-12">
      <Panel title="Findings intelligence" note="Search, filter, inspect, and triage findings" className="lg:col-span-8" action={<Link to="/findings" className="flex items-center gap-1 text-[10px] text-primary">All findings <ArrowRight size={12}/></Link>}><div className="mb-3 flex flex-wrap gap-2"><div className="relative min-w-[160px] flex-1"><Search size={13} className="absolute left-2.5 top-2.5 text-muted-foreground"/><input aria-label="Search findings" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search findings or assets" className="h-8 w-full rounded border border-border bg-secondary pl-8 pr-2 text-[11px] text-foreground placeholder:text-muted-foreground"/></div><div className="relative"><Filter size={12} className="pointer-events-none absolute left-2 top-2.5 text-muted-foreground"/><select aria-label="Filter severity" value={severity} onChange={e => setSeverity(e.target.value)} className="h-8 rounded border border-border bg-secondary pl-7 pr-2 text-[11px] text-foreground"><option value="All">All severity</option>{severityOrder.map(s => <option key={s} value={s}>{s}</option>)}</select></div></div><div className="overflow-x-auto"><table className="w-full min-w-[540px] text-left text-[11px]"><thead><tr className="border-b border-border text-[10px] uppercase text-muted-foreground"><th className="pb-2 font-medium">Finding</th><th className="pb-2 font-medium">Severity</th><th className="pb-2 font-medium">Asset</th><th className="pb-2 font-medium">Status</th><th className="pb-2 text-right font-medium">Inspect</th></tr></thead><tbody>{filtered.map(f => <tr key={f.id} className="border-b border-border/60 last:border-0 hover:bg-panel-hover"><td className="py-2.5 pr-2"><span className="block font-medium text-foreground">{f.title}</span><span className="text-[9px] text-muted-foreground">{f.id}</span></td><td className="pr-2"><Badge tone={f.severity}>{f.severity}</Badge></td><td className="max-w-[145px] truncate pr-2 text-muted-foreground">{f.asset}</td><td className="pr-2"><Badge tone={f.status}>{f.status}</Badge></td><td className="text-right"><Button variant="ghost" size="icon" className="h-7 w-7" title={`Inspect ${f.title}`} aria-label={`Inspect ${f.title}`} onClick={() => setSelected(f)}><ArrowRight size={13}/></Button></td></tr>)}</tbody></table>{filtered.length === 0 && <div className="py-8 text-center text-xs text-muted-foreground">No findings match your search.</div>}</div></Panel>
      <Panel title="Operations feed" note="Latest assessment events" className="lg:col-span-4"><div className="space-y-0">{[{icon:Siren, title:'Critical issue detected', desc:'Authorization check · FND-001', tone:'critical', time:'09:42'}, {icon:Radar, title:'Assessment running', desc:'API Security Assessment', tone:'primary', time:'09:18'}, {icon:CheckCircle2, title:'Fix verified', desc:'Content Security Policy', tone:'success', time:'Yesterday'}, {icon:Target, title:'Exposure mapped', desc:'Core API · 91 risk score', tone:'high', time:'Yesterday'}, {icon:Bell, title:'Report generated', desc:'Executive Security Report', tone:'low', time:'2 days ago'}].map((e,i) => <div key={i} className="flex gap-3 border-l border-border pb-4 pl-3 last:pb-0"><span className={`-ml-[18px] grid h-3 w-3 shrink-0 place-items-center rounded-full bg-${e.tone} ring-4 ring-panel`}/><div className="min-w-0 flex-1"><div className="flex justify-between gap-2 text-[11px]"><span className="truncate font-medium">{e.title}</span><span className="shrink-0 text-[9px] text-muted-foreground">{e.time}</span></div><p className="mt-1 truncate text-[10px] text-muted-foreground">{e.desc}</p></div></div>)}</div><Link to="/reports" className="mt-4 inline-flex items-center gap-1 border-t border-border pt-3 text-[10px] text-primary">View reports <ArrowRight size={12}/></Link></Panel>
    </div>
    <div className="flex flex-wrap items-center justify-between gap-2 border-t border-border pt-3 text-[10px] text-muted-foreground"><span>Sentinel Security Operations · Demonstration workspace</span><span>Sample data only — not a live security feed</span></div>
    <Dialog open={Boolean(selected)} onOpenChange={open => { if (!open) setSelected(null); }}><DialogContent className="max-w-lg border-border bg-panel text-foreground"><DialogHeader><DialogTitle className="pr-6 text-lg">{selected?.title}</DialogTitle></DialogHeader>{selected && <div className="space-y-4 text-xs"><div className="flex flex-wrap items-center gap-2"><Badge tone={selected.severity}>{selected.severity}</Badge><Badge tone={selected.status}>{selected.status}</Badge><span className="text-muted-foreground">{selected.id} · CVSS {selected.cvss}</span></div><div><div className="mb-1 text-[10px] uppercase text-muted-foreground">Asset</div><div>{selected.asset}</div></div><div><div className="mb-1 text-[10px] uppercase text-muted-foreground">Summary</div><p className="leading-relaxed text-muted-foreground">{selected.summary}</p></div><div><div className="mb-1 text-[10px] uppercase text-muted-foreground">Recommended fix</div><p className="leading-relaxed text-muted-foreground">{selected.fix}</p></div><div className="flex justify-between border-t border-border pt-4"><Button variant="outline" size="sm" onClick={() => statusAction(selected)}>{selected.status === 'Verified' ? 'Reopen finding' : 'Mark verified'}</Button><Button size="sm" asChild><Link to="/findings/$id" params={{ id: selected.id }}>Full investigation <ArrowRight size={13}/></Link></Button></div></div>}</DialogContent></Dialog>
  </div>;
}
